### PR TITLE
add meal page

### LINKED ISSUE #9: Meal Page
### Main Tasks:
- [x] Create header with return back button
- [x] Link return back button with the previous page (country meals page)
- [x] Add meal image
- [x] Create 'ingredients' section, every ingredient with its measure 
- [x] Create 'recipe' section
- [x] Add recipe video 
- [x] Style the page
- [x] Make the page responsive 

**Expected time:** 5h

### Page Design:
04  Meal

### PR DESCRIPTION
**Pull request by Ahmed-Sameer97**

### CODE REVIEW

**Review by mo7mad4 — APPROVED** [review]
## wow❤

**Review by sara219 — COMMENTED** [review]
Well done, amazing design 

but I have a question for all of you, the recipes and other data should appear from the API call!
Why didn't you do it (API fetch) while working on the pages, and had to deal with dummy data instead?

@Ahmed-Sameer97  @emanjaber  @mo7mad4  @RihamHasan

**Comment by emanjaber** [comment]
> Well done, amazing design
> 
> but I have a question for all of you, the recipes and other data should appear from the API call!
> Why didn't you do it (API fetch) while working on the pages, and had to deal with dummy data instead?


@sara219  We have not used the APIs yet, this work is only as HTML & CSS to see the initial look of the site. From tomorrow we will start working on the APIs part using JavaScript and certainly we will replace these codes and we will get the information from the APIs.

**Comment by sara219** [comment]
> @sara219 We have not used the APIs yet, this work is only as HTML & CSS to see the initial look of the site. From tomorrow we will start working on the APIs part using JavaScript and certainly we will replace these codes and we will get the information from the APIs.

Oh, I see, 
Tamam.

**Comment by Ahmed-Sameer97** [comment]
Thanks for the guidance 
This is preliminary  application design, tomorrow we will write js code which will fetch the results (recipe) by API.

**Comment by sara219** [comment]
> Thanks for the guidance
> This is preliminary application design, tomorrow we will write js code which will fetch the results (recipe) by API.

sounds great

**Review by sara219 — APPROVED** [review]

**Review by RihamHasan — APPROVED** [review]

**Review by emanjaber — APPROVED** [review]

**Pull request merged**
